### ISSUE TITLE
demo url is broken

### ISSUE THREAD

**Issue by adn-z** [dinoflorenzi/THOMSON-MO-TO-SOUNDCARD#2]
[SN76489AN SOUND CARD DEVELOPMENT](https://github.com/dinoflorenzi/THOMSON-MO-TO-SOUNDCARD/wiki/SN76489AN-MOTO-SOUND-CARD)

Sound track realized by ADNZ demo url is broken, use this url 
(https://oxustudio.com/to8/forum/audios/SN76489-TO8.mp4)

:)

**Comment by dinoflorenzi** [comment]
Link updated.
Thank you very much ADNZ🙂

**Comment by dinoflorenzi** [comment]
Closed

**Comment by dinoflorenzi** [comment]
Closed
